version: '3.7'
services:
  ui:
    container_name: ui
    build:
      context: ./ui
      dockerfile: dockerfile
    networks:
      - backend
    volumes:
      - ./ui:/ui
      - /ui/node_modules
    ports:
      - '80:80'
    environment:
      - NODE_ENV=development
    links:
      - api
    stdin_open: true
    tty: true  
  api:
    container_name: api
    restart: always
    build: 
      context: ./api
      dockerfile: dockerfile
    networks:
      - backend
    ports:
      - '5000:5000'
    volumes:
      - ./api:/api
      - /api/node_modules
networks:
  backend:
    driver: bridge