# build environment
FROM node:14.7.0-alpine as build
# install and cache app dependencies
COPY package.json package-lock.json ./
RUN npm install --only=prod&&npm install react-scripts@3.4.3 &&  mkdir /ui && mv ./node_modules ./ui
WORKDIR /ui
COPY . ./
RUN yarn build

# production environment
FROM nginx:stable-alpine
COPY --from=build /ui/build /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]