# build environment
FROM node:14.7.0-alpine as build
WORKDIR /ui
ENV PATH /ui/node_modules/.bin:$PATH
COPY package*.json /ui/
RUN npm install --silent
COPY . /ui/
CMD ["npm","run","build"]

FROM nginx:stable-alpine
COPY --from=build /ui/build /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY --from=build /ui/default.conf /etc/nginx/conf.d
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]