# build environment
FROM node:14.7.0-alpine as build
# install and cache app dependencies
COPY package.json package-lock.json ./
RUN mkdir /api && mv ./node_modules ./api
WORKDIR /api
COPY . ./
CMD ["npm", "run", "start"]